### ISSUE TITLE
Citizens Skins Suggestion

### ISSUE THREAD

**Issue by MCPanem** [CitizensDev/Citizens#1093]
Would it be possible to add a folder to add skins for names, instead of using minecraft's names for the skins? For my server there are lots of names being used that are all have the default skins, but for a female name that is kinda odd. I am not sure how easy/hard this would be, but I think many people would love it.

**Comment by TheGurw** [comment]
http://dev.bukkit.org/server-mods/citizenskins/

Requires Spout to work, but would anyway.

**Comment by Siggy999** [comment]
Requires Spout - but SkinStuff works for Citizens 1.2 - and as TheGurw mentioned - citizenskins works for 2.0

http://forums.spout.org/threads/admn-misc-rpg-skinsstuff-1-0-0-spn-1212-cb1-2-5-r4-0.3830/

**Comment by MCPanem** [comment]
There is no way to just have this in the normal version? without spout needed? (I would assume that you would have to us spoutcraft also.)

**Comment by Siggy999** [comment]
No, to my knowledge there isn't a way to do this without the spout plugin.  And yes, to use either of these solutions requires the user to log into the server using SpoutCraft.

I used the spoutcraft updater, which works very well. I gets it's own copy of minecraft to do what it needs to do, and I can still use my original whenever I like. I honestly don't find it any hassle whatsoever and really don't understand the resistance to needing spout on some servers.

**Comment by jwebbdev** [comment]
The resistance is that it requires extra action on the users part so is a barrier for players, that being said, you can't do it without a client-side mod.  The basic reason is that the client only knows to pull skins from usernames, it doesn't ask the server anything about it, so the server can't give the client somewhere else to look.

It would be very useful in a lot of cases if Mojang added the ability for the client to ask the server where to find some default skins, but unless that happens you're stuck forcing your clients to use a modified client.  (Not a huge hurdle, but often times one they'll just ignore your server and go elsewhere due to)

**Comment by fullwall** [comment]
Can't do this without Spout.
