### ISSUE TITLE
Me Following me

### ISSUE THREAD

**Issue by choyiny** [CitizensDev/Citizens#358]
When I created an NPC with my name, then relog minecraft, the NPC starts following me until i reset the citizens folder

**Comment by JochemKuijpers** [comment]
You can select the NPC with /npc list and then /npc select <ID>.
Then remove it with /npc remove

Then you have to restart your server because you'll be getting End of Stream errors.

Then it's fine without resetting the whole plugin.

**Comment by choyiny** [comment]
Really. Its the clone of me. Follows me. And at anytime I make my own NPC. Can you possibly fix it?!

**Comment by JochemKuijpers** [comment]
Yes, I think it is because the position of a player is managed by it's name. If you have the same name, so will your position be. The NPC is constantly trying to get to your position, but because of serverlag it is always a little behind.

I have a suggestion how to fix this, but that is the programmer's decision ofcourse. In Essentials (and some other plugins), players can have nicknames. If you create NPCs, give them a name like: NPC_<number> and a nickname as you wanted the NPC to be named. This will also fix any of the renaming bugs and glitches because the NPC name will in fact be the same, only it's nickname will be changed.

**Comment by fullwall** [comment]
This is fixed in latest dev builds already.
