### ISSUE TITLE
[Request] Npc Messages In order

### ISSUE THREAD

**Issue by HeXas** [CitizensDev/Citizens#868]
Hello, I recently created a server, and I had new ideas, I don't wanna use signs anymore for rules, etc, your plugin gave me a huge advantage on creating a RPG server, your plugin has all that its needed, but i'm having a slight problem, whenever I create an npc, used /npc set for msg, and npc /add for more messages, they're sometimes not in order for players who just came to server, I tested it with another account, rather than saying Hello, Adventurer which is the beginning, It skips to a random one and continuing the next message which comes after the random one ...any help?, well if the user right clicks the npc until it says Hello, Adventurer, messages are in order, so can you fix this? thanks

**Comment by l1amm** [comment]
CLOSE THIS ISSUE!
This is not an issue, the plugin isn't supposed to function that way.

It leaves off where the last person talked to it... The text the npc says is shared between players.
Why dont u make a quest instead and just use a time and location objective for each text. (go to location of npc, wait 5 seconds, ect)
This place is being flooded by people who don't understand the plugin and you guys are drowning the real issues that ACTUALLY need to be addressed because their functionality is not working AS INTENDED. No wonder he stopped responding here.

**Comment by Fureniku** [comment]
Add delays in. Edit the config file for your npc and add "<delay=20>your text here" - It'll make a new line 1 second later with that text. 40 is 2 seconds etc. - player could just walk past the NPC once then wander around - they'd still get the entire speech even if they teleported a thousand blocks away.

**Comment by HeXas** [comment]
Thanks Alot Flenix :), Helped me alot
